export default function languageList() {
  return [
    "Abkhazian",
    "Afar",
    "Afrikaans",
    "Akan",
    "Albanian",
    "Amharic",
    "Arabic",
    "Aragonese",
    "Armenian",
    "Assamese",
    "Avaric",
    "Avestan",
    "Aymara",
    "Azerbaijani",
    "Bambara",
    "Bashkir",
    "Basque",
    "Belarusian",
    "Bengali (Bangla)",
    "Bihari",
    "Bislama",
    "Bosnian",
    "Breton",
    "Bulgarian",
    "Burmese",
    "Catalan",
    "Chamorro",
    "Chechen",
    "Chichewa, Chewa, Nyanja",
    "Chinese",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Chuvash",
    "Cornish",
    "Corsican",
    "Cree",
    "Croatian",
    "Czech",
    "Danish",
    "Divehi, Dhivehi, Maldivian",
    "Dutch",
    "Dzongkha",
    "English",
    "Esperanto",
    "Estonian",
    "Ewe",
    "Faroese",
    "Fijian",
    "Finnish",
    "French",
    "Fula, Fulah, Pulaar, Pular",
    "Galician",
    "Gaelic (Scottish)",
    "Gaelic (Manx)",
    "Georgian",
    "German",
    "Greek",
    "Greenlandic",
    "Guarani",
    "Gujarati",
    "Haitian Creole",
    "Hausa",
    "Hebrew",
    "Herero",
    "Hindi",
    "Hiri Motu",
    "Hungarian",
    "Icelandic",
    "Ido",
    "Igbo",
    "Indonesian",
    "Interlingua",
    "Interlingue",
    "Inuktitut",
    "Inupiak",
    "Irish",
    "Italian",
    "Japanese",
    "Javanese",
    "Kalaallisut, Greenlandic",
    "Kannada",
    "Kanuri",
    "Kashmiri",
    "Kazakh",
    "Khmer",
    "Kikuyu",
    "Kinyarwanda (Rwanda)",
    "Kirundi",
    "Kyrgyz",
    "Komi",
    "Kongo",
    "Korean",
    "Kurdish",
    "Kwanyama",
    "Lao",
    "Latin",
    "Latvian (Lettish)",
    "Limburgish ( Limburger)",
    "Lingala",
    "Lithuanian",
    "Luga-Katanga",
    "Luganda, Ganda",
    "Luxembourgish",
    "Manx",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Maori",
    "Marathi",
    "Marshallese",
    "Moldavian",
    "Mongolian",
    "Nauru",
    "Navajo",
    "Ndonga",
    "Northern Ndebele",
    "Nepali",
    "Norwegian",
    "Norwegian bokmål",
    "Norwegian nynorsk",
    "Nuosu",
    "Occitan",
    "Ojibwe",
    "Old Church Slavonic, Old Bulgarian",
    "Oriya",
    "Oromo (Afaan Oromo)",
    "Ossetian",
    "Pāli",
    "Pashto, Pushto",
    "Persian (Farsi)",
    "Polish",
    "Portuguese",
    "Punjabi (Eastern)",
    "Quechua",
    "Romansh",
    "Romanian",
    "Russian",
    "Sami",
    "Samoan",
    "Sango",
    "Sanskrit",
    "Serbian",
    "Serbo-Croatian",
    "Sesotho",
    "Setswana",
    "Shona",
    "Sichuan Yi",
    "Sindhi",
    "Sinhalese",
    "Siswati",
    "Slovak",
    "Slovenian",
    "Somali",
    "Southern Ndebele",
    "Spanish",
    "Sundanese",
    "Swahili (Kiswahili)",
    "Swati",
    "Swedish",
    "Tagalog",
    "Tahitian",
    "Tajik",
    "Tamil",
    "Tatar",
    "Telugu",
    "Thai",
    "Tibetan",
    "Tigrinya",
    "Tonga",
    "Tsonga",
    "Turkish",
    "Turkmen",
    "Twi",
    "Uyghur",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Venda",
    "Vietnamese",
    "Volapük",
    "Wallon",
    "Welsh",
    "Wolof",
    "Western Frisian",
    "Xhosa",
    "Yiddish",
    "Yoruba",
    "Zhuang, Chuang",
    "Zulu",
  ];
}
